// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoLV6HZE4edQNs3JyJs0DZkF9-N_aGjfw',
    appId: '1:944662989828:web:97a92a3a29cc10d0d0f951',
    messagingSenderId: '944662989828',
    projectId: 'tracking-56023',
    authDomain: 'tracking-56023.firebaseapp.com',
    storageBucket: 'tracking-56023.appspot.com',
    measurementId: 'G-YTME46T8KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-jJ_hWNtUyXEjSC9plnmLd8l82_2y9aY',
    appId: '1:944662989828:android:3e188b74f63ec17ed0f951',
    messagingSenderId: '944662989828',
    projectId: 'tracking-56023',
    storageBucket: 'tracking-56023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOStZSSfLp_yMyvJyurOjsR4qLZ1V67cE',
    appId: '1:944662989828:ios:a9db56f393350ccfd0f951',
    messagingSenderId: '944662989828',
    projectId: 'tracking-56023',
    storageBucket: 'tracking-56023.appspot.com',
    iosBundleId: 'com.example.pTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOStZSSfLp_yMyvJyurOjsR4qLZ1V67cE',
    appId: '1:944662989828:ios:c552880925d468d8d0f951',
    messagingSenderId: '944662989828',
    projectId: 'tracking-56023',
    storageBucket: 'tracking-56023.appspot.com',
    iosBundleId: 'com.example.pTracking.RunnerTests',
  );
}
